--- !ruby/object:Jumpstart::Configuration
application_name: MyLocalFood
business_name: MyLocalFood, LLC
domain: mylocalfood.app
support_email: support@mylocalfood.app
default_from_email: MyLocalFood <support@mylocalfood.app>
business_address: |-
  415 W Salem Canal Rd
  Salem, UT 84653
background_job_processor: sidekiq
email_provider: mailgun
personal_accounts: false
livereload: false
